#!/bin/bash
set -e

export ARK_API_KEY=$(python3 -c "import json; print(json.load(open('/Users/leifu/Movies/dramas/.cursor/mcp.json'))['mcpServers']['volc-ark']['env']['ARK_API_KEY'])")

PROJECT_ROOT="/Users/leifu/Movies/dramas/dramas/我和爸妈互换人生"
SCRIPT="/Users/leifu/Movies/dramas/mcps/volc-ark/scripts/ark_seedream_image.py"
LOOKS_DIR="$PROJECT_ROOT/assets/looks"
mkdir -p "$LOOKS_DIR"

PASS=0
FAIL=0
FAILED_LIST=""

generate_char() {
    local id="$1"
    local name="$2"
    local prompt="$3"
    local extra_args="$4"

    echo ""
    echo "=========================================="
    echo "Generating: $id ($name)"
    echo "=========================================="
    if python3 "$SCRIPT" generate \
        --prompt "$prompt" \
        --output "$LOOKS_DIR/${id}.png" \
        --ratio "9:16" \
        $extra_args; then
        echo "✅ $id ($name) — SUCCESS"
        PASS=$((PASS + 1))
    else
        echo "❌ $id ($name) — FAILED"
        FAIL=$((FAIL + 1))
        FAILED_LIST="$FAILED_LIST $id"
    fi
}

# ===== MAIN CHARACTERS =====

generate_char "CHAR-001-L01" "林小夏" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 18-year-old Chinese woman, a high school senior. perfectly symmetrical facial features, level lip line, centered features. oval face with softly defined jawline, slightly chubby cheeks giving a youthful fullness. large expressive almond-shaped eyes with natural double eyelid crease, bright dark brown irises with natural catchlight. natural soft arched brows, slightly thick, untrimmed adolescent brows. small delicate nose with a slightly rounded tip. naturally full rosy lips, symmetrically shaped. warm fair skin with a slight sun-kissed tone, youthful healthy glow. tall enough adolescent build with natural feminine curves beginning to develop (163cm), slim waist, slightly soft around the arms, NOT a child but a physically mature teenager with adolescent proportions, energetic youthful posture. dark brown-black hair pulled into a neat shoulder-length ponytail, loose strands framing the face, hair tie is a simple black elastic. wearing standard Chinese high school uniform: white button-up shirt, navy blue blazer with school crest embroidered on left chest, navy blue pleated skirt reaching just above the knees, white canvas sneakers. carrying a well-worn dark navy canvas backpack covered in colorful hand-placed stickers and small patches on the front pocket. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-002-L01" "苏敏" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 45-year-old Chinese woman, a full-time mother and former elementary school teacher. perfectly symmetrical facial features, level lip line, centered features. oval face with soft round contours showing gentle aging with slight nasolabial folds forming. warm dark brown eyes with visible fine crow's feet at corners, double eyelid crease, gaze carries both tenderness and a persistent undercurrent of worry. soft natural brows, slightly thin from years of minimal grooming, groomed but not over-plucked. small well-proportioned nose with slightly rounded tip. thin to medium lips, slightly dry, natural color, symmetrically shaped. fair warm-toned complexion with slight sallowness from years of indoor housework, fine lines around eyes and forehead. practical chin-length bob cut, hair tucked behind ears, dark black hair with a few visible strands of gray at the temples. average build with soft midsection (160cm), slightly rounded shoulders from habitual housework posture but carries herself with quiet dignity, graceful feminine proportions, natural confident stance. wearing a warm beige V-neck knit cardigan over a white crew-neck T-shirt, khaki straight-leg casual trousers, light brown flat shoes. on left wrist: a well-worn women's analog watch with small face and leather strap. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-003-L01" "林建国" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 47-year-old Chinese man, a mid-level manager at a manufacturing company, a quiet devoted father. perfectly symmetrical facial features, level lip line, centered features. square-shaped face with softened jawline, a dignified middle-aged Chinese male face. slightly small deep-set eyes behind glasses, double eyelid, warm but tired gaze. thick straight brows slightly unkempt, natural gray beginning to show. broad nose bridge, medium height, well-proportioned. thin lips with slightly darker natural color, habitually pressed together. fair yellow-toned complexion, visible pores, slight dark circles under eyes, clean-shaven. neat short crop with slightly receding hairline at the temples, sides trimmed shorter, top combed to the side, black hair with visible gray at the temples. stocky medium build with broad shoulders and slight belly (175cm), slightly hunched posture but stands with quiet dignity when aware, natural proportions. wearing a light blue long-sleeve dress shirt with top button undone, dark gray dress trousers, black leather belt, dark brown lace-up leather shoes. medium-sized rounded rectangular silver-framed glasses. a ballpoint pen barely visible in the shirt breast pocket. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-004-L01" "林大宇" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 24-year-old Chinese man, a startup co-founder and full-stack engineer. perfectly symmetrical facial features, level lip line, centered features. lean angular face with sharp defined jawline and clean masculine bone structure. narrow phoenix eyes with a sharp confident gaze, single eyelid or subtle inner fold, intense dark brown irises. sharp sword-like brows, clean and naturally defined. high straight nose bridge, well-defined prominent masculine feature. thin lips with a natural slight upturn at corners, often in a confident smirk. fair healthy complexion, clear skin with natural texture, clean-shaven with sharp jaw definition visible. textured short crop with sides tapered, top slightly longer styled with matte hair product for natural messy texture, dark black hair. lean athletic build with broad shoulders tapering to a narrow waist (180cm), V-taper physique, toned but not bulky, confident assertive posture, shoulders back with natural youthful energy. wearing a solid black crew-neck T-shirt, dark blue slim-fit jeans, white minimalist sneakers. a small geometric-line tattoo approximately 5cm on the outer left forearm. a small wireless Bluetooth earbud in left ear. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-005-L01" "赵美兰" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 72-year-old Chinese woman, a grandmother with sharp eyes and a warm commanding presence. perfectly symmetrical facial features, level lip line, centered features. oval face with soft rounded contours, elegant aging with pronounced nasolabial folds and laugh lines mapping a life well-lived. bright alert eyes radiating sharp intelligence despite age, slight epicanthic fold, dark brown irises with an unmistakable knowing sparkle. gray-white brows, naturally sparse but neatly groomed, slightly arched. small well-proportioned nose, slightly broadened with age. thin lips with deep smile lines extending from the corners, natural color slightly faded. fair elderly complexion with visible age spots and fine wrinkles, skin is clean and well-maintained with healthy warm undertone. silver-white hair neatly pulled into a traditional low bun at the back, a few loose wisps framing the forehead, every strand clean and in place. slender but upright build (158cm), stands remarkably straight for her age, NOT frail or hunched, carries herself with quiet authority, natural dignified posture. wearing a rich purple-red traditional Chinese quilted jacket with mandarin collar and fabric knot buttons, subtle floral-and-bird jacquard pattern in the fabric, dark straight-leg trousers, black traditional cloth shoes. on left wrist: a classic round gold bangle bracelet with surface wear marks from decades of daily wear. in right hand resting at her side: a bamboo walking cane. holding ONE single vintage dark brown leather-bound diary approximately A5 size with visible natural grain texture, creased and softened from decades of handling, small tarnished brass clasp. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
"--image-url https://drama-reference-images.tos-cn-beijing.volces.com/props/我和爸妈互换人生/PROP-001.png"

generate_char "CHAR-006-L01" "王铁军" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 52-year-old Chinese man, a veteran high school homeroom teacher known for his strict but caring nature. perfectly symmetrical facial features, level lip line, centered features. square-shaped face with strong defined jawline, a classic authoritative Chinese male face. medium-sized eyes with sharp penetrating gaze, inner double eyelid, look of perpetual seriousness. thick straight dense brows that naturally furrow, giving a permanently stern expression. broad nose bridge, straight and prominent, strong masculine feature. thin tight lips, habitually pressed together. healthy tan complexion from years of outdoor school yard supervision, visible sun damage and weathering, rough but clean skin texture. military-style buzz cut, sides and back clippered very short, top slightly longer but still very short, jet black mixed with significant gray. solid stocky build with broad shoulders (178cm), upright military-like posture, stands with hands clasped behind his back, strong athletic frame, commanding presence. wearing a dark gray zip-up jacket with collar, light-colored dress shirt underneath, black straight-leg trousers, black leather casual shoes. on left wrist: an old-style black digital watch. a red correcting pen visible in the jacket breast pocket. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-007-L01" "陈雨晴" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 18-year-old Chinese woman, a high school senior and the best friend of the protagonist, radiating sunshine energy. perfectly symmetrical facial features, level lip line, centered features. round face with soft oval proportions, youthful adorable appearance with gentle chin. large round eyes that sparkle with natural brightness, clear double eyelid crease, eyes naturally curve into crescents when she smiles. natural soft arched brows, slightly thick, friendly approachable look. small cute nose with slightly upturned tip. naturally full lips with upturned corners, a face built for smiling. fair porcelain-smooth skin with warm healthy glow, youthful radiant complexion, even skin tone. medium-length dark brown-black shoulder-length hair styled in two low pigtails secured with simple black elastics, bangs naturally parted and slightly wavy, hair has natural sheen and volume. petite well-proportioned figure (160cm), slim with natural youthful curves, energetic posture leaning slightly forward, natural confident stance. wearing the same standard Chinese high school uniform: white button-up shirt, navy blue blazer, navy blue pleated skirt, white canvas sneakers. two colorful hair clips in hair — one rainbow-colored and one blue. small star-shaped stud earrings in both ears. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-008-L01" "张明远" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 26-year-old Chinese man, a startup co-founder who transitioned from engineering to business, quietly intellectual. perfectly symmetrical facial features, level lip line, centered features. lean oval face with defined but not sharp jawline, intellectual slightly bookish appearance. medium-sized eyes behind black-framed glasses, single eyelid with a focused steady gaze. straight level brows, slightly thin, naturally furrowed in concentration. straight nose bridge, medium height and proportion. thin but not tight lips, neutral expression. fair natural complexion, clear healthy skin. neat side-parted hair with bangs reaching the eyebrows, combed naturally to the right, deep black hair, clean and tidy but not over-styled. lean slim build (175cm), narrow shoulders but good upright posture, the physique of someone who maintains basic fitness despite desk work. wearing a light gray plaid long-sleeve button-up shirt with sleeves casually rolled up to the forearms, white crew-neck T-shirt underneath, dark khaki casual trousers, gray canvas shoes. medium-sized black rectangular-framed glasses. carrying a gray laptop backpack on both shoulders. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

# ===== GROUP ACTORS =====

generate_char "CHAR-GRP-01-L01" "赵宇晨" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 18-year-old Chinese man, a high school senior and top math student. perfectly symmetrical facial features, level lip line, centered features. oval face with slightly angular jawline showing early adult bone structure, clean-cut studious appearance. medium-sized almond-shaped eyes with a gentle intelligent gaze, double eyelid crease. neat straight brows, well-groomed. straight nose bridge, medium proportion. thin lips with a shy slightly upturned smile. fair clear skin with healthy adolescent complexion. neat short hair, side-parted, well-groomed student look, dark black hair. tall lean adolescent build (175cm), good posture, slim and slightly gangly, the frame of a growing teenager. wearing the same Chinese high school uniform: white button-up shirt, navy blue blazer, navy blue trousers, white sneakers. holding a math textbook in one hand. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-GRP-02-L01" "老刘" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A approximately 50-year-old Chinese man, a veteran office worker with 20 years of loyal service. perfectly symmetrical facial features, level lip line, centered features. round square face with soft jowls, kind weathered face of a man who has spent decades in middle management. slightly small eyes with warm gentle gaze, double eyelid crease. thick brows with significant gray. broad nose, average proportions. full lips, naturally downturned at rest but quick to smile. fair yellow-toned complexion with visible aging, crow's feet, forehead lines. short neat graying hair, slightly thinning on top, conservative side-parted style. stocky average build (172cm), slight beer belly, comfortable posture of a man at ease in his own skin. wearing a white dress shirt slightly wrinkled from a long day, dark blue trousers, black belt, black leather shoes. a worn company ID badge on a lanyard around his neck. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-GRP-03-L01" "刘阿姨" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A approximately 48-year-old Chinese woman, a primary school teacher and old colleague of the protagonist's mother. perfectly symmetrical facial features, level lip line, centered features. oval face with soft contours, warm approachable face of a caring educator. warm eyes with a kind gentle gaze, visible smile lines. naturally arched brows, well-groomed. small proportional nose. medium lips with a warm natural smile. fair warm-toned complexion with minimal aging, well-maintained. shoulder-length hair in a neat low ponytail, dark black with a few strands of gray, professional teacher look. average build (158cm), healthy weight, warm and welcoming posture. wearing a light-colored knit sweater, dark comfortable trousers, flat shoes — the practical comfortable style of an experienced teacher. wearing a pair of reading glasses on a chain around her neck. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-GRP-04-L01" "林思琪" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A approximately 24-year-old Chinese woman, a gentle and poised young professional. perfectly symmetrical facial features, level lip line, centered features. oval face with refined elegant contours, naturally beautiful. large clear eyes with a gentle warm gaze, double eyelid crease. naturally arched elegant brows. straight nose bridge with refined proportions. naturally rosy full lips, gentle smile. fair luminous skin with natural healthy glow. long straight dark black hair falling past the shoulders, neatly maintained with natural shine, parted in the middle. tall slender graceful figure (165cm), elegant posture, naturally poised. wearing a soft cream-colored knit sweater, light blue denim jeans, white sneakers — casual but put-together young professional style. carrying a small crossbody bag. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

generate_char "CHAR-GRP-05-L01" "王奶奶" \
"Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A approximately 75-year-old Chinese woman, a kind elderly neighbor. perfectly symmetrical facial features, level lip line, centered features. round face with deep wrinkles and age spots, kind grandmotherly face. small eyes with a warm gentle gaze, heavily hooded with age. sparse gray brows. small nose slightly broadened with age. thin lips with deep smile lines. fair elderly complexion with visible age spots, thin papery skin texture. short gray hair permed in a traditional elderly Chinese style, neatly set. small slightly stooped build (155cm), frail but with a warm presence. wearing a traditional floral-print quilted jacket in muted colors, dark comfortable trousers, black cloth shoes. Vertical 9:16, photorealistic costume reference, modern Chinese city 2024, warm natural lighting, cinematic composition, realistic photograph, cinematic lighting, NOT anime, NOT cartoon, NOT illustration, NOT manga." \
""

# ===== SUMMARY =====
echo ""
echo "=========================================="
echo "GENERATION COMPLETE"
echo "=========================================="
echo "✅ Passed: $PASS"
echo "❌ Failed: $FAIL"
if [ -n "$FAILED_LIST" ]; then
    echo "Failed IDs: $FAILED_LIST"
fi
echo "=========================================="
