#!/bin/zsh
# SCENE-003B 收购站档口特写 · 生成脚本（prompt 与 资产/场景卡片.md SCENE-003B 条目逐字一致）
cd /Users/lei/Movies/demo1

PROMPT='Close-up frontal view of a scrap-purchase stall counter window at the shadowed end of a scavenger shantytown street at dusk, tight oppressive composition: a narrow low service window set into a wall of mismatched corrugated hull plates, thick vertical iron bars dark with rust framing a cramped dim booth interior, camera at customer eye level so the mean little window presses down on the viewer, behind the bars only an empty battered metal stool and deep shadow where the clerk would sit, a scarred counter plate of salvaged starship hull juts through beneath the bars polished pale by years of transactions, on the counter a battered brass balance scale with chained weighing pans, beside it a shallow dented metal tray holding thin dull metal tokens, a wire-mesh basket of mixed rusty scrap iron dumped on the countertop, above the window a crude vulture totem sign hammered from blackened scrap metal with spread wings, purely sculptural with no lettering, a blank scratched slate board hanging beside the window wiped empty showing only meaningless scratch marks where prices would be chalked, one caged hanging lamp inside the booth casting a greasy warm pool of light over scale and token tray, warm rust-orange dusk light from the street mixing with faint cyan and pink reflections of patched neon tubes on the wet metal, thin steam and dust haze drifting past, stingy monopoly atmosphere of the only buyer in town. Cinematic photorealistic sci-fi wasteland, desaturated rust-orange palette with dusty haze, rusted metal textures with glowing accents, film grain, vertical 9:16 composition. Empty stall, no people, no human figures, no faces, no silhouettes, no hands, no mannequins, no readable text, no lettering, no numbers, no characters of any language anywhere, the slate board and every sign surface blank with only scratches. NOT inscribed with any characters or text. No watermark, no logo.'

python3 mcps/volc-ark/scripts/ark_seedream_image.py generate \
  --prompt "$PROMPT" \
  --size 1600x2848 \
  --output "dramas/流放荒星后，我靠捡破烂富甲星际/assets/scenes/SCENE-003B.png"
