#!/bin/bash
# Character L01 Generation Script
# Project: 闪婚后她马甲掉了

set -e
export ARK_API_KEY=$(python3 -c "import json; print(json.load(open('/Users/leifu/Movies/dramas/.cursor/mcp.json'))['mcpServers']['volc-ark']['env']['ARK_API_KEY'])")

SCRIPT="/Users/leifu/Movies/dramas/mcps/volc-ark/scripts/ark_seedream_image.py"
OUT="/Users/leifu/Movies/dramas/dramas/闪婚后她马甲掉了/assets/looks"
PROP007="https://drama-reference-images.tos-cn-beijing.volces.com/props/闪婚后她马甲掉了/PROP-007.png"

echo "=== Generating CHAR-001-L01 (苏锦) with PROP-007 reference ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 26-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Oval face with refined delicate bone structure, large expressive almond-shaped eyes with dark brown iris and natural catchlight, sharp defined sword-like brows with subtle arch, high straight delicate nose bridge, full symmetrical soft lips with natural pale pink tone, fair luminous skin with natural dewy glow and visible skin texture. Long straight deep black hair reaching waist level with natural silky sheen, center-parted, falling naturally over shoulders. Tall and slender with graceful feminine proportions (168cm), slim waist with elegant S-curve silhouette, elegant confident poised posture. Wearing a minimalist cream-colored cashmere sweater with relaxed fit, dark gray high-waisted wide-leg trousers, beige flat slip-on shoes. ONE single antique jade pendant on a faded dark red silk cord at the neck, the pendant is a smooth oval celadon green nephrite disc approximately 5cm across with the character "方" carved in regular script. Subtle spiritual light in the eyes suggesting hidden depth. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, subsurface scattering, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --image-url "$PROP007" \
  --output "$OUT/CHAR-001-L01.png"

echo "=== Generating CHAR-002-L01 (陆晋川) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 28-year-old Chinese man, perfectly symmetrical facial features, level lip line, centered features. Angular masculine bone structure with sharp defined jawline, deep intense phoenix eyes with black iris and commanding presence, thick sharp sword-like brows, high straight strong nose bridge, thin defined lips with clear lip line and symmetrical corners, healthy warm-toned skin with natural texture and clean-shaven sharp jaw definition. Short black hair with left side part, clean sharp hairline, well-groomed neat style. Tall athletic build (183cm) with broad shoulders tapering to lean waist, V-taper physique, powerful elegant frame, commanding upright posture with shoulders back and natural authority. Wearing a fitted dark charcoal turtleneck sweater, black tailored slim trousers, black leather dress shoes. ONE single matte black titanium sport watch on the left wrist. Subtle intensity in the gaze suggesting concealed power. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, subsurface scattering, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-002-L01.png"

echo "=== Generating CHAR-003-L01 (赵美兰) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 55-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Melon-seed face with slightly prominent cheekbones, narrow sharp phoenix eyes with upturned outer corners and piercing gaze, high groomed arched brows with semi-permanent makeup trace, straight nose bridge with narrow nostrils, thin lips painted with bold red lipstick, fair well-maintained skin with visible nasolabial folds and subtle crow'\''s feet showing age gracefully. Shoulder-length dark brown wavy permed hair with volume and bounce, styled in soft waves framing the face. Average height with well-maintained slightly full figure (163cm), upright haughty posture with chin slightly raised. Wearing a burgundy velvet cropped jacket with gold-tone buttons over a black fitted sheath dress, gold low-heel leather shoes. ONE single thick gold chain necklace at the neck, jade drop earrings on both ears, ONE single jade bangle bracelet on the left wrist. Arrogant condescending expression with narrowed eyes. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-003-L01.png"

echo "=== Generating CHAR-004-L01 (陆思琪) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 24-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Heart-shaped face with pointed delicate chin, large round double-eyelid eyes with thick lashes and bright innocent gaze, soft arched brows, small delicate upturned nose, full plump lips with glossy pink lip glaze, fair dewy skin with flawless makeup and natural blush on cheeks. Long light chestnut brown wavy hair in loose large curls falling past the shoulders with volume and bounce. Slender well-proportioned youthful figure (165cm), slim waist with natural feminine curves, playful slightly tilted posture. Wearing a pink double-breasted cropped blazer over a white pleated mini skirt, white pointed-toe low-heel pumps. ONE single pink designer handbag held in the right hand, small crystal stud earrings on both ears. Sweet innocent smile with a hint of mischief in the eyes. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-004-L01.png"

echo "=== Generating CHAR-005-L01 (钱福) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 50-year-old Chinese man, perfectly symmetrical facial features, level lip line, centered features. Oblong face with moderate angular features, narrow deep-set eyes with restrained watchful gaze, straight thick brows, medium-height straight nose bridge, thin lips with corners slightly upturned in a practiced professional smile, yellowish healthy skin tone with natural texture and subtle age lines. Short dark gray-black hair neatly combed with side part, clean groomed appearance. Average build with lean upright frame (175cm), professional erect posture with hands clasped in front. Wearing a well-tailored black three-piece suit with vest, white dress shirt, dark gray silk tie, black polished leather dress shoes. ONE single silver fountain pen clipped to the breast pocket. Restrained watchful expression with a veneer of deference. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-005-L01.png"

echo "=== Generating CHAR-006-L01 (苏婉) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 25-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Round face with soft rounded chin, almond-shaped eyes slightly round with calculating gaze, refined arched brows slightly overdone, small slightly flat nose bridge, medium fullness lips with rose-colored lipstick, fair skin with heavy foundation makeup and subtle contouring. Dark brown center-parted long straight hair with inward-curved ends reaching mid-back. Well-proportioned slightly curvy figure (164cm), deliberate figure-showing posture with one hand on hip. Wearing a light purple floral chiffon blouse tucked into a beige A-line skirt, nude pointed-toe high heels. ONE single delicate thin gold chain necklace at the collarbone, ONE single designer watch on the left wrist. Sweet artificial smile that does not reach the eyes. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-006-L01.png"

echo "=== Generating CHAR-007-L01 (顾衍) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 30-year-old Chinese man, perfectly symmetrical facial features, level lip line, centered features. Oval face with soft yet defined bone structure, warm deep almond-shaped eyes with brown iris and gentle intellectual gaze, soft arched brows, straight refined nose bridge, medium fullness lips with corners gently upturned in a restrained warm smile, fair smooth skin with natural texture and scholarly pallor. Short black hair with side part and a few loose strands falling across the forehead. Tall lean scholarly build (180cm), slender with upright elegant posture and relaxed shoulders. Wearing a light blue dress shirt with top button undone, dark gray tailored trousers, brown leather dress shoes. ONE single pair of gold-rimmed thin-frame eyeglasses on the nose, ONE single white medical lab coat draped over the left arm. Gentle warm expression with a trace of melancholy in the eyes. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-007-L01.png"

echo "=== Generating CHAR-008-L01 (沈瑶) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 25-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Round face with full apple cheeks and youthful charm, large round crescent-shaped eyes that crinkle when smiling with dark brown iris and natural sparkle, natural thick straight brows, small round upturned button nose, full smiling lips with coral lip glaze showing a bright genuine smile, warm healthy skin tone with natural rosy glow and dewy texture. Black shoulder-length short bob hair with slightly upturned ends and wispy air bangs across the forehead. Petite yet well-proportioned figure (160cm), slim with energetic youthful posture and slightly bouncy stance. Wearing an oversized goose-yellow hoodie, light blue cropped denim jeans, white canvas sneakers. ONE single bright yellow canvas crossbody bag with a short strap on the right shoulder. Radiant cheerful expression with eyes squeezed slightly from smiling. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-008-L01.png"

echo "=== Generating CHAR-009-L01 (方雅琴) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 52-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Oval face with soft refined contours, gentle almond-shaped eyes with subtle crow'\''s feet and warm emotional gaze with slight moisture, soft natural brows, elegant straight nose bridge, medium fullness lips with muted rose lipstick, fair porcelain-smooth skin exceptionally well-maintained for her age with natural texture. Dark gray shoulder-length straight hair with slightly curved ends, elegant and sophisticated styling. Tall slender elegant figure (166cm), graceful poised upright posture with natural dignity. Wearing a long cream-white cashmere coat over a dark navy silk blouse, black wide-leg trousers, black low-heel leather shoes. ONE single pair of pearl drop earrings, ONE single jade bangle on the right wrist. Warm dignified expression with underlying depth of emotion. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-009-L01.png"

echo "=== Generating CHAR-010-L01 (陆伯恒) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 55-year-old Chinese man, perfectly symmetrical facial features, level lip line, centered features. Round face with subtle double chin, small squinting eyes with shrewd gleaming gaze, short thick bushy brows, round bulbous nose tip, full thick lips with a smug insincere smile, oily shiny complexion with visible enlarged pores and ruddy tone. Short black hair with receding hairline and slicked-back greasy styling. Stocky slightly overweight build (172cm) with beer belly visible through clothing, self-satisfied swagger posture. Wearing a slightly tight dark navy pinstripe suit jacket, white dress shirt stretched at the buttons, red silk tie, black leather dress shoes. ONE single thick gold watch on the left wrist. Smug greedy expression with eyes narrowing calculatingly. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-010-L01.png"

echo "=== Generating CHAR-011-L01 (顾林秀英) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 65-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Oblong face with high prominent cheekbones, deep-set small sharp eyes with piercing knife-like gaze, sparse gray thin brows, thin aquiline nose with high sharp bridge, thin downturned lips with corners curving downward in perpetual disapproval, pale dry skin with visible deep wrinkles and age spots. Silver-white short hair pulled back tightly into a severe bun at the back of the head. Thin wiry strong frame (158cm), rigid commanding posture with spine straight and chin elevated. Wearing a dark purple traditional Chinese mandarin-collar jacket with frog button closures, black long skirt, black cloth shoes. ONE single ebony wood walking cane held in the right hand as an authority symbol, not for support. Stern imperious expression radiating unquestionable authority. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-011-L01.png"

echo "=== Generating CHAR-012-L01 (陈诗韵) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 26-year-old Chinese woman, perfectly symmetrical facial features, level lip line, centered features. Elongated oval face with pointed chin, seductive upturned cat-like eyes with heavy false lashes and smoky eye makeup, high arched dark brows, straight narrow nose, full plump red lips with bold crimson lipstick, very fair skin with heavy glamorous makeup including contouring and highlighter. Dark chestnut brown long wavy hair in large voluminous curls falling past the chest. Tall curvaceous figure (168cm) with pronounced S-curve silhouette, deliberately provocative posture with hand on hip and slight hip sway. Wearing a tight-fitting red V-neck knee-length bodycon dress, black pointed-toe stiletto high heels. Large gold hoop earrings on both ears, red nail polish on fingernails. Sultry seductive expression with half-lidded eyes and parted lips. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-012-L01.png"

echo "=== Generating CHAR-013-L01 (陆父) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 60-year-old Chinese man, perfectly symmetrical facial features, level lip line, centered features. Oblong face with defined cheekbones and weathered dignity, deep-set gentle phoenix eyes with slightly sunken eye sockets and warm melancholic gaze, gray long sparse brows, high straight nose bridge, thin lips with slightly downturned corners conveying lifelong regret, yellowish skin with visible deep wrinkles and age lines showing a life of burden. Short silver-gray hair neatly combed back, clean refined appearance. Thin yet upright frame (178cm), still carrying himself with scholarly dignity despite age, slightly stooped shoulders suggesting weight of guilt. Wearing a beige linen blazer over a light blue turtleneck sweater, dark gray tailored trousers, brown leather dress shoes. ONE single pair of reading glasses hanging from a thin chain around the neck. Weary dignified expression with profound regret in the eyes. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-013-L01.png"

echo "=== Generating CHAR-014-L01 (苏父) ==="
python3 "$SCRIPT" generate \
  --prompt 'Photorealistic costume reference, wide shot showing entire figure from head to toe with feet and shoes clearly visible at the bottom edge of the frame, single person standing upright facing the camera, plain white background, clean flat studio lighting. Full body fully visible, not cropped. A 55-year-old Chinese man, perfectly symmetrical facial features, level lip line, centered features. Round fleshy face with soft undefined features, round eyes with visible eye bags and timid uncertain gaze, sparse thin pale brows, flat round-tipped nose, thick lips with slightly downturned corners, yellowish rough skin with visible pores and uneven tone. Thinning sparse black hair with severely receding hairline, poorly groomed. Slightly overweight soft build (170cm) with paunch belly, slouched defeated posture lacking confidence and presence. Wearing a wrinkled light gray suit jacket with slight stain on the lapel, white dress shirt with collar slightly open and untucked, loose poorly knotted tie, old scuffed black leather dress shoes. Timid nervous expression with eyes darting slightly and shoulders hunched. Shot on 85mm lens, editorial portrait photograph, natural skin texture with visible pores, shallow depth of field, photorealistic, cinematic lighting, 9:16 vertical frame, urban luxury aesthetic, modern Chinese city setting, realistic photograph, NOT anime, NOT cartoon, NOT illustration, NOT manga.' \
  --ratio "9:16" \
  --output "$OUT/CHAR-014-L01.png"

echo ""
echo "=== ALL 14 CHARACTERS GENERATED ==="
echo "Checking output files:"
ls -la "$OUT/"/*.png 2>/dev/null | wc -l
echo "files generated"
ls -la "$OUT/"
